config/routes.rb
Rails.application.routes.draw do
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :body,  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def show
    @task = Task.find(params[:id])
  end
  

  def index
    @tasks = Task.all
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @tasks = Task.all
    if @task.save
    redirect_to tasks_path
    else
      render :index
    end
  end

  def edit
    @task = Task.find(params[:id])
    
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
    redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end


  private

  def task_params
    params.require(:task).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naito036Task</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>タスク登録</h1>
<% if @task.errors.any? %>
  <p><b><font color="red">【エラー内容】</font></b></p>
  <% @task.errors.full_messages.each do |message| %>
    <li><font color="red"><%= message %></font></li>
  <% end %>
  
<% end %>

<%= form_with model: @task, local: true do |form| %>
  <p>
    タイトル<br>
    <%= form.text_field :title %>
  </p>
  <p>
    内容<br>
    <%= form.text_area :body %>
  </p>

  <%= form.submit "Update Task" %>
<% end %>

<p>
  <%= link_to "詳細に戻る", task_path(@task) %>
</p>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, task %>|<%= link_to "削除", task, method: :delete %></li>
  <% end %>
</ul>
<hr>

<h2>タスク登録</h2>
<% if @task.errors.any? %>
  <p><b><font color="red">【エラー内容】</font></b></p>
  <% @task.errors.full_messages.each do |message| %>
    <li><font color="red"><%= message %></font></li>
  <% end %>
  
<% end %>

<%= form_with model: @task, local: true do |form| %>
  <p>
    タイトル<br>
    <%= form.text_field :title %>
  </p>
  <p>
    内容<br>
    <%= form.text_area :body %>
  </p>

  <%= form.submit "Create Task" %>
<% end %>

app/views/tasks/new.html.erb
<h1>タスク登録</h1>
<% if @task.errors.any? %>
  <p><b>【エラー内容】</b></p>
  <% @task.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

<%= form_with model: @task, local: true do |form| %>
  <p>
    タイトル<br>
    <%= form.text_field :title %>
  </p>
  <p>
    内容<br>
    <%= form.text_area :body %>
  </p>

  <%= form.submit "Create Task" %>
<% end %>

app/views/tasks/show.html.erb
<h1>タスク詳細</h1>

<p>
  <b>【タイトル】<br><%= @task.title %></b>
</p>

<p>
  <b>【内容】<br><%= @task.body %></b>
</p>


  <%= link_to "編集", edit_task_path(@task) %>


  <%= link_to "削除", task_path, method: :delete %>


  <%= link_to "戻る", tasks_path(@task) %>